export * from "./Home";
export * from "./About";
export * from "./Blogs";
export * from "./Contact";
export * from "./Menu";
export * from "./Portfolio";
export * from "./OneBlog";
export * from "./Login";
export * from "./Registration";
export * from "./Cart";
export * from "./Reservation"
